import { Restaurant } from "./types";

const IMAGES = [
  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4",
  "https://images.unsplash.com/photo-1555396273-367ea4eb4db5",
  "https://images.unsplash.com/photo-1544148103-0773bf10d330",
  "https://images.unsplash.com/photo-1504674900247-0877df9cc836",
  "https://images.unsplash.com/photo-1559339352-11d035aa65de",
  "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38",
];

const DEFAULT_TIMES = [
  "4:30 PM",
  "4:45 PM",
  "5:00 PM",
  "7:45 PM",
  "8:00 PM",
  "8:15 PM",
];

export const restaurants: Restaurant[] = [
  // PARK CITY
  {
    id: "1",
    name: "Osteria Bella",
    cuisine: "Italian",
    rating: 4.8,
    priceLevel: 3,
    image: IMAGES[0],
    location: "Park City",
    description: "Handmade pastas and seasonal ingredients.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "2",
    name: "Summit Izakaya",
    cuisine: "Japanese",
    rating: 4.7,
    priceLevel: 3,
    image: IMAGES[1],
    location: "Park City",
    description: "Modern izakaya with sushi and robata.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },
  {
    id: "3",
    name: "Le Petit Bistro",
    cuisine: "French",
    rating: 4.7,
    priceLevel: 3,
    image: IMAGES[2],
    location: "Park City",
    description: "Classic French cuisine.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "4",
    name: "Alpine Social",
    cuisine: "Modern American",
    rating: 4.6,
    priceLevel: 3,
    image: IMAGES[3],
    location: "Park City",
    description: "Elevated comfort food and cocktails.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },

  // HEBER
  {
    id: "5",
    name: "Wasatch Grill House",
    cuisine: "Steakhouse",
    rating: 4.6,
    priceLevel: 3,
    image: IMAGES[4],
    location: "Heber City",
    description: "Hearty steaks and grilled favorites.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "6",
    name: "Heber Harvest Kitchen",
    cuisine: "Farm-to-Table",
    rating: 4.7,
    priceLevel: 2,
    image: IMAGES[5],
    location: "Heber City",
    description: "Fresh seasonal dishes.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 10,
  },
  {
    id: "7",
    name: "Ridgeview Café",
    cuisine: "Brunch",
    rating: 4.5,
    priceLevel: 2,
    image: IMAGES[0],
    location: "Heber City",
    description: "Cozy café with comfort classics.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "8",
    name: "Backcountry Smokehouse",
    cuisine: "BBQ",
    rating: 4.6,
    priceLevel: 2,
    image: IMAGES[1],
    location: "Heber City",
    description: "Slow-smoked BBQ.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },

  // KAMAS
  {
    id: "9",
    name: "Timberline Kitchen",
    cuisine: "Comfort Food",
    rating: 4.5,
    priceLevel: 2,
    image: IMAGES[2],
    location: "Kamas",
    description: "Cozy comfort food spot.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "10",
    name: "High Valley Grill",
    cuisine: "American",
    rating: 4.4,
    priceLevel: 2,
    image: IMAGES[3],
    location: "Kamas",
    description: "Classic grill favorites.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },
  {
    id: "11",
    name: "Pine Creek Pizza Co.",
    cuisine: "Pizza",
    rating: 4.6,
    priceLevel: 1,
    image: IMAGES[4],
    location: "Kamas",
    description: "Hand-tossed pizzas.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "12",
    name: "Summit Valley Diner",
    cuisine: "Diner",
    rating: 4.3,
    priceLevel: 1,
    image: IMAGES[5],
    location: "Kamas",
    description: "Classic diner meals.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 10,
  },

  // SLC
  {
    id: "13",
    name: "Ember Social",
    cuisine: "Modern American",
    rating: 4.7,
    priceLevel: 4,
    image: IMAGES[0],
    location: "Salt Lake City",
    description: "Trendy dining and cocktails.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "14",
    name: "Lotus Street Kitchen",
    cuisine: "Asian Fusion",
    rating: 4.6,
    priceLevel: 3,
    image: IMAGES[1],
    location: "Salt Lake City",
    description: "Modern Asian flavors.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },
  {
    id: "15",
    name: "Urban Fork",
    cuisine: "American",
    rating: 4.5,
    priceLevel: 3,
    image: IMAGES[2],
    location: "Salt Lake City",
    description: "Seasonal modern dining.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "16",
    name: "Copper Owl",
    cuisine: "Gastropub",
    rating: 4.6,
    priceLevel: 3,
    image: IMAGES[3],
    location: "Salt Lake City",
    description: "Upscale pub and cocktails.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },
];

export const filterChips = [
  "Park City",
  "Heber City",
  "Kamas",
  "Salt Lake City",
];
