import { Restaurant } from "./types";

export const restaurants: Restaurant[] = [
  {
    id: "1",
    name: "Osteria Bella",
    cuisine: "Italian",
    rating: 4.8,
    priceLevel: 3,
    image: "/images/restaurant-1.jpg",
    location: "West Village, NYC",
    description: "A sophisticated Italian dining experience featuring handmade pastas and seasonal ingredients sourced from local farms. Our intimate setting offers the perfect ambiance for special occasions.",
    availableTimes: ["5:30 PM", "6:00 PM", "7:30 PM", "8:00 PM"],
    perk: "Dining Credit",
    perkAmount: 15,
  },
  {
    id: "2",
    name: "Sakura Omakase",
    cuisine: "Japanese",
    rating: 4.9,
    priceLevel: 4,
    image: "/images/restaurant-2.jpg",
    location: "Tribeca, NYC",
    description: "Experience the art of omakase with Chef Tanaka's 12-course tasting menu. Each piece is crafted with fish flown in daily from Tokyo's Tsukiji Market.",
    availableTimes: ["6:00 PM", "8:30 PM", "9:00 PM"],
    perk: "Dining Credit",
    perkAmount: 25,
  },
  {
    id: "3",
    name: "Le Petit Bistro",
    cuisine: "French",
    rating: 4.7,
    priceLevel: 3,
    image: "/images/restaurant-3.jpg",
    location: "Upper East Side, NYC",
    description: "Classic French cuisine in an elegant Parisian-inspired setting. Our menu showcases traditional techniques with a modern sensibility.",
    availableTimes: ["5:00 PM", "6:30 PM", "7:00 PM", "8:30 PM"],
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "4",
    name: "Prime & Co.",
    cuisine: "American",
    rating: 4.6,
    priceLevel: 4,
    image: "/images/restaurant-4.jpg",
    location: "Midtown, NYC",
    description: "A contemporary steakhouse featuring prime cuts dry-aged in-house for 45 days. Our wine cellar boasts over 500 selections from around the world.",
    availableTimes: ["5:30 PM", "6:00 PM", "7:00 PM", "9:00 PM"],
    perk: "Dining Credit",
    perkAmount: 20,
  },
];

export const filterChips = [
  "Tonight",
  "2 Guests",
  "Nearby",
  "Italian",
  "Japanese",
  "$$$",
  "Dining Credit",
];
