import { Restaurant } from "./types";

const DEFAULT_IMAGE =
  "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4";

const DEFAULT_TIMES = [
  "4:30 PM",
  "4:45 PM",
  "5:00 PM",
  "7:45 PM",
  "8:00 PM",
  "8:15 PM",
];

export const restaurants: Restaurant[] = [
  // PARK CITY
  {
    id: "1",
    name: "Osteria Bella",
    cuisine: "Italian",
    rating: 4.8,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Park City",
    description:
      "A sophisticated Italian dining experience featuring handmade pastas and seasonal ingredients sourced from local farms.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "2",
    name: "Summit Izakaya",
    cuisine: "Japanese",
    rating: 4.7,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Park City",
    description:
      "Modern Japanese izakaya with sushi, robata, and craft sake in a warm mountain setting.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },
  {
    id: "3",
    name: "Le Petit Bistro",
    cuisine: "French",
    rating: 4.7,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Park City",
    description:
      "Classic French cuisine in an elegant Parisian-inspired setting.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "4",
    name: "Alpine Social",
    cuisine: "Modern American",
    rating: 4.6,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Park City",
    description:
      "Elevated comfort food, shareable plates, and handcrafted cocktails.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },

  // HEBER CITY
  {
    id: "5",
    name: "Wasatch Grill House",
    cuisine: "American / Steakhouse",
    rating: 4.6,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Heber City",
    description:
      "Rustic mountain dining with hearty steaks and grilled favorites.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "6",
    name: "Heber Harvest Kitchen",
    cuisine: "Farm-to-Table",
    rating: 4.7,
    priceLevel: 2,
    image: DEFAULT_IMAGE,
    location: "Heber City",
    description: "Fresh local ingredients crafted into seasonal dishes.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 10,
  },
  {
    id: "7",
    name: "Ridgeview Café",
    cuisine: "Brunch / American",
    rating: 4.5,
    priceLevel: 2,
    image: DEFAULT_IMAGE,
    location: "Heber City",
    description:
      "A cozy café known for breakfast favorites and comfort classics.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "8",
    name: "Backcountry Smokehouse",
    cuisine: "BBQ",
    rating: 4.6,
    priceLevel: 2,
    image: DEFAULT_IMAGE,
    location: "Heber City",
    description:
      "Slow-smoked meats and bold BBQ flavors in a laid-back setting.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },

  // KAMAS
  {
    id: "9",
    name: "Timberline Kitchen",
    cuisine: "Comfort Food",
    rating: 4.5,
    priceLevel: 2,
    image: DEFAULT_IMAGE,
    location: "Kamas",
    description: "Cozy spot serving elevated comfort food for locals.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "10",
    name: "High Valley Grill",
    cuisine: "American",
    rating: 4.4,
    priceLevel: 2,
    image: DEFAULT_IMAGE,
    location: "Kamas",
    description:
      "Classic American grill with hearty portions and friendly vibes.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },
  {
    id: "11",
    name: "Pine Creek Pizza Co.",
    cuisine: "Pizza",
    rating: 4.6,
    priceLevel: 1,
    image: DEFAULT_IMAGE,
    location: "Kamas",
    description: "Hand-tossed pizzas with fresh toppings and crispy crust.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "12",
    name: "Summit Valley Diner",
    cuisine: "Diner",
    rating: 4.3,
    priceLevel: 1,
    image: DEFAULT_IMAGE,
    location: "Kamas",
    description: "Classic diner with burgers, shakes, and comfort meals.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 10,
  },

  // SALT LAKE CITY
  {
    id: "13",
    name: "Ember Social",
    cuisine: "Modern American",
    rating: 4.7,
    priceLevel: 4,
    image: DEFAULT_IMAGE,
    location: "Salt Lake City",
    description:
      "Trendy downtown vibe with craft cocktails and shareable plates.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 10,
  },
  {
    id: "14",
    name: "Lotus Street Kitchen",
    cuisine: "Asian Fusion",
    rating: 4.6,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Salt Lake City",
    description: "Bold Asian flavors with a modern street food twist.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 15,
  },
  {
    id: "15",
    name: "Urban Fork",
    cuisine: "American",
    rating: 4.5,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Salt Lake City",
    description:
      "Contemporary dining with seasonal menus and vibrant atmosphere.",
    availableTimes: DEFAULT_TIMES,
    perk: "Dining Credit",
    perkAmount: 5,
  },
  {
    id: "16",
    name: "Copper Owl",
    cuisine: "Gastropub",
    rating: 4.6,
    priceLevel: 3,
    image: DEFAULT_IMAGE,
    location: "Salt Lake City",
    description:
      "Upscale pub fare paired with craft beers and signature cocktails.",
    availableTimes: DEFAULT_TIMES,
    perk: "% Off",
    perkAmount: 20,
  },
];

export const filterChips = [
  "Tonight",
  "2 Guests",
  "Nearby",
  "Park City",
  "Heber City",
  "Kamas",
  "Salt Lake City",
  "Italian",
  "Japanese",
  "Dining Credit",
  "% Off",
];
